# github.com/x448/helix-config-toml
theme = "dark_plus"  # dark_plus works well with hx --tutor.

[editor]
color-modes = true
line-number = "relative"
mouse = true
bufferline = "multiple" # Show currently open buffers, only when more than one exists.
cursorline = true # Highlight all lines with a cursor
# Show a ruler at column 120
#rulers = [120]

[editor.indent-guides]
render = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
ret = ["move_line_down", "goto_first_nonwhitespace"]
0   = "goto_line_start"
X = "select_line_above"

[keys.select]
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]
0   = "goto_line_start"
X = "select_line_above"
